import type { Faculty, Category, Student } from '@/types';

export const faculties: Faculty[] = [
  'İqtisadiyyat və İdarəetmə',
  'Mühəndislik',
  'Tibb',
  'Memarlıq',
  'Pedaqoji',
  'Sosial İdarəetmə və Hüquq',
  'Beynəlxalq Münasibətlər və Xarici Dillər',
  'İncəsənət',
];

export const categories: Category[] = [
  'STEM',
  'Humanitar',
  'İncəsənət',
  'İdman',
  'Sahibkarlıq',
  'Texnologiya',
];

export const students: Student[] = [
  {
    id: '1',
    name: 'Aylin',
    surname: 'Məmmədova',
    faculty: 'Mühəndislik',
    major: 'Kompüter Mühəndisliyi',
    course: 3,
    profilePictureUrl: 'https://picsum.photos/seed/6/400/400',
    profilePictureHint: 'woman coding',
    skills: ['React', 'Node.js', 'Python', 'Machine Learning', 'UI/UX'],
    mainCategory: 'Texnologiya',
    projects: [
      {
        title: 'Tələbə Portalı',
        description: 'Universitet üçün müasir tələbə portalının hazırlanması.',
        role: 'Frontend Developer',
        link: 'https://github.com',
      },
    ],
    achievements: [
      {
        name: 'Technofest 2023',
        position: '1-ci yer',
        date: '2023-05-10',
        level: 'Beynəlxalq',
      },
    ],
    socialLinks: {
      linkedin: '#',
      github: '#',
    },
    talentScore: 95,
    joinDate: '2024-05-20T10:00:00Z',
  },
  {
    id: '2',
    name: 'Orxan',
    surname: 'Əliyev',
    faculty: 'İqtisadiyyat və İdarəetmə',
    major: 'Biznesin İdarə Edilməsi',
    course: 4,
    profilePictureUrl: 'https://picsum.photos/seed/9/400/400',
    profilePictureHint: 'entrepreneur pitch',
    skills: ['Marketinq', 'Biznes Analizi', 'Layihə İdarəçiliyi', 'Maliyyə'],
    mainCategory: 'Sahibkarlıq',
    projects: [
      {
        title: 'Startap "EduPlatform"',
        description: 'Təhsil texnologiyaları sahəsində yeni startap layihəsi.',
        role: 'Qurucu',
      },
    ],
    achievements: [
      {
        name: 'Global Startup Weekend',
        position: 'Finalist',
        date: '2023-11-20',
        level: 'Beynəlxalq',
      },
    ],
    socialLinks: {
      linkedin: '#',
    },
    talentScore: 92,
    joinDate: '2024-05-18T14:30:00Z',
  },
  {
    id: '3',
    name: 'Nərgiz',
    surname: 'Hüseynova',
    faculty: 'İncəsənət',
    major: 'Qrafik Dizayn',
    course: 2,
    profilePictureUrl: 'https://picsum.photos/seed/8/400/400',
    profilePictureHint: 'person painting',
    skills: ['Adobe Photoshop', 'Illustrator', 'Brendinq', 'Veb Dizayn'],
    mainCategory: 'İncəsənət',
    projects: [],
    achievements: [
      {
        name: 'Milli Dizayn Müsabiqəsi',
        position: '2-ci yer',
        date: '2024-02-15',
        level: 'Respublika',
      },
    ],
    socialLinks: {
      behance: '#',
      instagram: '#',
    },
    talentScore: 88,
    joinDate: '2024-05-21T09:00:00Z',
  },
  {
    id: '4',
    name: 'Kənan',
    surname: 'İbrahimov',
    faculty: 'Tibb',
    major: 'Ümumi Tibb',
    course: 4,
    profilePictureUrl: 'https://picsum.photos/seed/7/400/400',
    profilePictureHint: 'man science',
    skills: ['Biotexnologiya', 'Genetika', 'Elmi Tədqiqat'],
    mainCategory: 'STEM',
    projects: [
      {
        title: 'Genetik Xəstəliklər Araşdırması',
        description: 'Nadir genetik xəstəliklərin molekulyar əsaslarının tədqiqi.',
        role: 'Tədqiqatçı',
      },
    ],
    achievements: [],
    socialLinks: {
      linkedin: '#',
    },
    talentScore: 85,
    joinDate: '2024-04-15T11:00:00Z',
  },
  {
    id: '5',
    name: 'Fatimə',
    surname: 'Quliyeva',
    faculty: 'Sosial İdarəetmə və Hüquq',
    major: 'Hüquqşünaslıq',
    course: 3,
    profilePictureUrl: 'https://picsum.photos/seed/1/400/400',
    profilePictureHint: 'female student',
    skills: ['Mülki Hüquq', 'Cinayət Hüququ', 'Debat', 'Analitik Düşüncə'],
    mainCategory: 'Humanitar',
    projects: [],
    achievements: [
      {
        name: 'Respublika Debat Forumu',
        position: 'Ən Yaxşı Spiker',
        date: '2023-10-05',
        level: 'Respublika',
      },
    ],
    socialLinks: {},
    talentScore: 82,
    joinDate: '2024-05-19T16:00:00Z',
  },
    {
    id: '6',
    name: 'Elvin',
    surname: 'Rəsulov',
    faculty: 'Memarlıq',
    major: 'Şəhərsalma',
    course: 4,
    profilePictureUrl: 'https://picsum.photos/seed/2/400/400',
    profilePictureHint: 'male student',
    skills: ['AutoCAD', '3ds Max', 'Urban Dizayn', 'Landşaft Memarlığı'],
    mainCategory: 'İncəsənət',
    projects: [],
    achievements: [],
    socialLinks: {
      portfolio: '#',
    },
    talentScore: 80,
    joinDate: '2024-03-25T12:00:00Z',
  },
];
